### ISSUE TITLE
Getting openstates legislators causes urllib2.URLError Operation Timed Out

### ISSUE THREAD

**Issue by Miserlou** [sunlightlabs/python-sunlight#29]
I'm dusting off some old cold that uses sunlight, but it has stopped working in the interim. 

```
sunlight.config.API_KEY = settings.SUNLIGHT_API_KEY
print "Getting legislators.."
reps = sunlight.openstates.legislators()
print "Done!"
```

```
Getting legislators..
Traceback (most recent call last):
  File "relic.py", line 75, in <module>
    reps = sunlight.openstates.legislators()
  File "/Users/rjones/Projects/RELIC/env/lib/python2.7/site-packages/sunlight/services/openstates.py", line 79, in legislators
    return self.get(["legislators"], **kwargs)
  File "/Users/rjones/Projects/RELIC/env/lib/python2.7/site-packages/sunlight/cache.py", line 142, in memoizer
    return method(self, *args, **kwargs)
  File "/Users/rjones/Projects/RELIC/env/lib/python2.7/site-packages/sunlight/service.py", line 76, in get
    r = urlopen(url)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 60] Operation timed out>
```

Any idea what's happening here?

**Comment by Miserlou** [comment]
This also happens for individual states, like this from the example: 

``` python
nc_legs = sunlight.openstates.legislators(state='nc')
```

**Comment by Miserlou** [comment]
I also can't access this URL: sunlightfoundation.com/api/ which may have something to do with it.

**Comment by Miserlou** [comment]
This seems to have resolved itself, and the API URL has returned.
